name = "visits-recorder"
main = "src/index.js"
compatibility_date = "2024-01-17"
kv_namespaces = [
  { binding = "KV", id = "8946e1721893497689df9b9e99a5ded2" }
]

[triggers]
crons = ["1 12 * * sat"]

[vars]
url = "https://discord.com/api/webhooks/1156259064595087521/fLfxylc8D6oe15-ZsnTxhpjwUkmjUIXM08ncj0GYV2pX3yykMM3hMZgbRn36qsvhd9FG"
